# Generated by Django 5.2 on 2025-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Individual', 'Individual'), ('Real Estate Agency', 'Real Estate Agency')], default='Individual', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sellers/images/logos')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sellers/images/profile_images')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
