# Generated by Django 4.2.21 on 2025-05-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_is_seller'),
        ('accounts', '0002_userfavorite'),
    ]

    operations = [
    ]
