# Generated by Django 5.2 on 2025-05-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_is_seller'),
        ('accounts', '0002_userfavorite'),
    ]

    operations = [
    ]
