# Generated by Django 5.2 on 2025-05-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=100)),
                ('bathrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('seller_profile_image', models.ImageField(blank=True, null=True, upload_to='seller_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
