# Generated by Django 4.0.4 on 2025-05-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='seller_images/')),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='is_published',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='category',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='badges',
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.seller'),
            preserve_default=False,
        ),
    ]
