# Generated by Django 5.2 on 2025-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(help_text='Size in square meters'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/images'),
        ),
    ]
