# Generated by Django 5.2 on 2025-05-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_price_alter_property_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='seller_profile_image_url',
        ),
        migrations.AddField(
            model_name='property',
            name='seller_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(help_text='Price in ISK'),
        ),
    ]
