# Generated by Django 4.0.4 on 2025-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
