# Generated by Django 4.0.4 on 2025-05-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='zip_code',
            new_name='zip',
        ),
    ]
