# Generated by Django 5.2 on 2025-05-13 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expired', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Contingent', 'Contingent'), ('Expired', 'Expired'), ('Finalized', 'Finalized'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('seller_name', models.CharField(max_length=255)),
                ('offer_price', models.IntegerField()),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_offers', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseFinalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(choices=[('Iceland', 'Iceland'), ('Norway', 'Norway'), ('Sweden', 'Sweden'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Estonia', 'Estonia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Poland', 'Poland')], default='Iceland', max_length=100)),
                ('national_id', models.CharField(help_text='National ID (kennitala)', max_length=20)),
                ('payment_option', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Mortgage', 'Mortgage')], max_length=50)),
                ('cardholder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('credit_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_card_expiry', models.CharField(blank=True, max_length=7, null=True)),
                ('credit_card_cvc', models.CharField(blank=True, max_length=4, null=True)),
                ('bank_account', models.CharField(blank=True, help_text='IBAN, Swift or Icelandic format', max_length=50, null=True)),
                ('mortgage_provider', models.CharField(blank=True, choices=[('Arion Banki', 'Arion Banki'), ('Landsbankinn', 'Landsbankinn'), ('Islandsbanki', 'Islandsbanki'), ('Bank of America', 'Bank of America'), ('Bank of Ireland', 'Bank of Ireland'), ('Citi', 'Citi'), ('HSBC', 'HSBC'), ('J.P. Morgan', 'J.P. Morgan'), ('Rabobank', 'Rabobank'), ('Santander', 'Santander'), ('Skandinavian Bank', 'Skandinavian Bank'), ('Swedbank', 'Swedbank'), ('U.S. Bank', 'U.S. Bank'), ('Vestbank', 'Vestbank')], max_length=100, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offers.purchaseoffer')),
            ],
        ),
    ]
