# Generated by Django 5.2 on 2025-05-13 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('sellers', '0002_seller_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseoffer',
            name='user',
        ),
        migrations.AddField(
            model_name='purchaseoffer',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_offers', to='sellers.seller'),
        ),
        migrations.AlterField(
            model_name='purchaseoffer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Contingent', 'Contingent')], default='Pending', max_length=50),
        ),
    ]
