# Generated by Django 5.2 on 2025-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoffer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Contingent', 'Contingent'), ('Expired', 'Expired'), ('Finalized', 'Finalized'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
