# Generated by Django 5.2 on 2025-05-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_purchaseoffer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasefinalization',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
