# Generated by Django 5.2 on 2025-05-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_purchasefinalization_credit_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasefinalization',
            name='bank_account',
            field=models.CharField(blank=True, default='', help_text='IBAN, Swift or Icelandic format', max_length=50),
        ),
        migrations.AlterField(
            model_name='purchasefinalization',
            name='cardholder_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchasefinalization',
            name='credit_card_cvc',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='purchasefinalization',
            name='credit_card_expiry',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='purchasefinalization',
            name='credit_card_number',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='purchasefinalization',
            name='mortgage_provider',
            field=models.CharField(blank=True, choices=[('Arion Banki', 'Arion Banki'), ('Landsbankinn', 'Landsbankinn'), ('Islandsbanki', 'Islandsbanki'), ('Bank of America', 'Bank of America'), ('Bank of Ireland', 'Bank of Ireland'), ('Citi', 'Citi'), ('HSBC', 'HSBC'), ('J.P. Morgan', 'J.P. Morgan'), ('Rabobank', 'Rabobank'), ('Santander', 'Santander'), ('Skandinavian Bank', 'Skandinavian Bank'), ('Swedbank', 'Swedbank'), ('U.S. Bank', 'U.S. Bank'), ('Vestbank', 'Vestbank')], default='', max_length=100),
        ),
    ]
